plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
}

loom {
    runs { client { client() } }
    mixin { useLegacyMixinAp = false }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}


tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}


processResources {
    def props = [
            mod_id                : project.mod_id,
            mod_name              : project.mod_name,
            version               : project.mod_version,
            mod_description       : project.mod_description,
            mod_authors           : project.mod_authors,
            mod_license           : project.mod_license,
            minecraft_version     : project.minecraft_version,
            fabric_loader_version : project.fabric_loader_version
    ]
    inputs.properties props

    filesMatching("fabric.mod.json") {
        expand props
    }
}
