minecraft_version=1.21.4
fabric_loader_version=0.16.9

mod_id=safespawn
mod_name=SafeSpawn
mod_version=1.0.1
mod_authors=Fragmented_Chaos
mod_license=MIT
mod_description=This mod restores MC-212 and MC-21650 (which were fixed in 24w45a), and also fixes MC-278261.
maven_group=com.fragmentedchaos.safespawn

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
