minecraft_version=26.1
neo_version=26.1.0.10-beta
minecraft_version_range=[26.1,)

mod_id=safespawn
mod_name=SafeSpawn
mod_version=1.0.2+neo-26.1plus
mod_authors=Fragmented_Chaos
mod_license=MIT
mod_description=This mod restores MC-212 and MC-21650 (which were fixed in 24w45a), and also fixes MC-278261.
maven_group=com.fragmentedchaos.safespawn

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
