modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "${mod_authors}"
logoFile = "icon.png"
displayURL = "https://modrinth.com/mod/safespawn"
issueTrackerURL = "https://github.com/Fragmented-Chaos/SafeSpawn/issues"
credits = "https://github.com/Fragmented-Chaos/SafeSpawn"

[[mixins]]
config = "safespawn.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange ="[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange ="${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
